name: Archive Blog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  archive-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Archive
        run: |
          wget -m -k -E -p -e robots=off https://walidcumo08-ahvpy.wordpress.com/

      - name: Commit and Push Archive
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Automated blog archive update"
          git push
